#pragma once

#include "wbpch.h"

#include "platform/vulkan/base.h"
#include "wb/graphics/types.h"

namespace wb {
    class TexFormatToVkFormatMapper {
    public:
        TexFormatToVkFormatMapper() {
            // clang-format off
            set(TEXTURE_FORMAT::UNKNOWN, VK_FORMAT_UNDEFINED);

            set(TEXTURE_FORMAT::RGBA32_TYPELESS, VK_FORMAT_R32G32B32A32_SFLOAT);
            set(TEXTURE_FORMAT::RGBA32_FLOAT, VK_FORMAT_R32G32B32A32_SFLOAT);
            set(TEXTURE_FORMAT::RGBA32_UINT, VK_FORMAT_R32G32B32A32_UINT);
            set(TEXTURE_FORMAT::RGBA32_SINT, VK_FORMAT_R32G32B32A32_SINT);

            set(TEXTURE_FORMAT::RGB32_TYPELESS, VK_FORMAT_R32G32B32_SFLOAT);
            set(TEXTURE_FORMAT::RGB32_FLOAT, VK_FORMAT_R32G32B32_SFLOAT);
            set(TEXTURE_FORMAT::RGB32_UINT, VK_FORMAT_R32G32B32_UINT);
            set(TEXTURE_FORMAT::RGB32_SINT, VK_FORMAT_R32G32B32_SINT);

            set(TEXTURE_FORMAT::RGBA16_TYPELESS, VK_FORMAT_R16G16B16A16_SFLOAT);
            set(TEXTURE_FORMAT::RGBA16_FLOAT, VK_FORMAT_R16G16B16A16_SFLOAT);
            set(TEXTURE_FORMAT::RGBA16_UNORM, VK_FORMAT_R16G16B16A16_UNORM);
            set(TEXTURE_FORMAT::RGBA16_UINT, VK_FORMAT_R16G16B16A16_UINT);
            set(TEXTURE_FORMAT::RGBA16_SNORM, VK_FORMAT_R16G16B16A16_SNORM);
            set(TEXTURE_FORMAT::RGBA16_SINT, VK_FORMAT_R16G16B16A16_SINT);

            set(TEXTURE_FORMAT::RG32_TYPELESS, VK_FORMAT_R32G32_SFLOAT);
            set(TEXTURE_FORMAT::RG32_FLOAT, VK_FORMAT_R32G32_SFLOAT);
            set(TEXTURE_FORMAT::RG32_UINT, VK_FORMAT_R32G32_UINT);
            set(TEXTURE_FORMAT::RG32_SINT, VK_FORMAT_R32G32_SINT);

            set(TEXTURE_FORMAT::R32G8X24_TYPELESS, VK_FORMAT_D32_SFLOAT_S8_UINT);
            set(TEXTURE_FORMAT::D32_FLOAT_S8X24_UINT, VK_FORMAT_D32_SFLOAT_S8_UINT);
            set(TEXTURE_FORMAT::R32_FLOAT_X8X24_TYPELESS, VK_FORMAT_D32_SFLOAT_S8_UINT);
            set(TEXTURE_FORMAT::X32_TYPELESS_G8X24_UINT, VK_FORMAT_UNDEFINED);

            set(TEXTURE_FORMAT::RGB10A2_TYPELESS, VK_FORMAT_A2R10G10B10_UNORM_PACK32);
            set(TEXTURE_FORMAT::RGB10A2_UNORM, VK_FORMAT_A2R10G10B10_UNORM_PACK32);
            set(TEXTURE_FORMAT::RGB10A2_UINT, VK_FORMAT_A2R10G10B10_UINT_PACK32);
            set(TEXTURE_FORMAT::R11G11B10_FLOAT, VK_FORMAT_B10G11R11_UFLOAT_PACK32);

            set(TEXTURE_FORMAT::RGBA8_TYPELESS, VK_FORMAT_R8G8B8A8_UNORM);
            set(TEXTURE_FORMAT::RGBA8_UNORM, VK_FORMAT_R8G8B8A8_UNORM);
            set(TEXTURE_FORMAT::RGBA8_UNORM_SRGB, VK_FORMAT_R8G8B8A8_SRGB);
            set(TEXTURE_FORMAT::RGBA8_UINT, VK_FORMAT_R8G8B8A8_UINT);
            set(TEXTURE_FORMAT::RGBA8_SNORM, VK_FORMAT_R8G8B8A8_SNORM);
            set(TEXTURE_FORMAT::RGBA8_SINT, VK_FORMAT_R8G8B8A8_SINT);

            set(TEXTURE_FORMAT::RG16_TYPELESS, VK_FORMAT_R16G16_SFLOAT);
            set(TEXTURE_FORMAT::RG16_FLOAT, VK_FORMAT_R16G16_SFLOAT);
            set(TEXTURE_FORMAT::RG16_UNORM, VK_FORMAT_R16G16_UNORM);
            set(TEXTURE_FORMAT::RG16_UINT, VK_FORMAT_R16G16_UINT);
            set(TEXTURE_FORMAT::RG16_SNORM, VK_FORMAT_R16G16_SNORM);
            set(TEXTURE_FORMAT::RG16_SINT, VK_FORMAT_R16G16_SINT);

            set(TEXTURE_FORMAT::R32_TYPELESS, VK_FORMAT_R32_SFLOAT);
            set(TEXTURE_FORMAT::D32_FLOAT, VK_FORMAT_D32_SFLOAT);
            set(TEXTURE_FORMAT::R32_FLOAT, VK_FORMAT_R32_SFLOAT);
            set(TEXTURE_FORMAT::R32_UINT, VK_FORMAT_R32_UINT);
            set(TEXTURE_FORMAT::R32_SINT, VK_FORMAT_R32_SINT);

            set(TEXTURE_FORMAT::R24G8_TYPELESS, VK_FORMAT_D24_UNORM_S8_UINT);
            set(TEXTURE_FORMAT::D24_UNORM_S8_UINT, VK_FORMAT_D24_UNORM_S8_UINT);
            set(TEXTURE_FORMAT::R24_UNORM_X8_TYPELESS, VK_FORMAT_D24_UNORM_S8_UINT);
            set(TEXTURE_FORMAT::X24_TYPELESS_G8_UINT, VK_FORMAT_UNDEFINED);

            set(TEXTURE_FORMAT::RG8_TYPELESS, VK_FORMAT_R8G8_UNORM);
            set(TEXTURE_FORMAT::RG8_UNORM, VK_FORMAT_R8G8_UNORM);
            set(TEXTURE_FORMAT::RG8_UINT, VK_FORMAT_R8G8_UINT);
            set(TEXTURE_FORMAT::RG8_SNORM, VK_FORMAT_R8G8_SNORM);
            set(TEXTURE_FORMAT::RG8_SINT, VK_FORMAT_R8G8_SINT);

            set(TEXTURE_FORMAT::R16_TYPELESS, VK_FORMAT_R16_SFLOAT);
            set(TEXTURE_FORMAT::R16_FLOAT, VK_FORMAT_R16_SFLOAT);
            set(TEXTURE_FORMAT::D16_UNORM, VK_FORMAT_D16_UNORM);
            set(TEXTURE_FORMAT::R16_UNORM, VK_FORMAT_R16_UNORM);
            set(TEXTURE_FORMAT::R16_UINT, VK_FORMAT_R16_UINT);
            set(TEXTURE_FORMAT::R16_SNORM, VK_FORMAT_R16_SNORM);
            set(TEXTURE_FORMAT::R16_SINT, VK_FORMAT_R16_SINT);

            set(TEXTURE_FORMAT::R8_TYPELESS, VK_FORMAT_R8_UNORM);
            set(TEXTURE_FORMAT::R8_UNORM, VK_FORMAT_R8_UNORM);
            set(TEXTURE_FORMAT::R8_UINT, VK_FORMAT_R8_UINT);
            set(TEXTURE_FORMAT::R8_SNORM, VK_FORMAT_R8_SNORM);
            set(TEXTURE_FORMAT::R8_SINT, VK_FORMAT_R8_SINT);
            set(TEXTURE_FORMAT::A8_UNORM, VK_FORMAT_UNDEFINED);

            set(TEXTURE_FORMAT::R1_UNORM, VK_FORMAT_UNDEFINED);

            set(TEXTURE_FORMAT::RGB9E5_SHAREDEXP, VK_FORMAT_E5B9G9R9_UFLOAT_PACK32);
            set(TEXTURE_FORMAT::RG8_B8G8_UNORM, VK_FORMAT_UNDEFINED);
            set(TEXTURE_FORMAT::G8R8_G8B8_UNORM, VK_FORMAT_UNDEFINED);

            // http://www.g-truc.net/post-0335.html
            // http://renderingpipeline.com/2012/07/texture-compression/
            set(TEXTURE_FORMAT::BC1_TYPELESS, VK_FORMAT_BC1_RGB_UNORM_BLOCK);
            set(TEXTURE_FORMAT::BC1_UNORM, VK_FORMAT_BC1_RGB_UNORM_BLOCK);
            set(TEXTURE_FORMAT::BC1_UNORM_SRGB, VK_FORMAT_BC1_RGB_SRGB_BLOCK);
            set(TEXTURE_FORMAT::BC2_TYPELESS, VK_FORMAT_BC2_UNORM_BLOCK);
            set(TEXTURE_FORMAT::BC2_UNORM, VK_FORMAT_BC2_UNORM_BLOCK);
            set(TEXTURE_FORMAT::BC2_UNORM_SRGB, VK_FORMAT_BC2_SRGB_BLOCK);
            set(TEXTURE_FORMAT::BC3_TYPELESS, VK_FORMAT_BC3_UNORM_BLOCK);
            set(TEXTURE_FORMAT::BC3_UNORM, VK_FORMAT_BC3_UNORM_BLOCK);
            set(TEXTURE_FORMAT::BC3_UNORM_SRGB, VK_FORMAT_BC3_SRGB_BLOCK);
            set(TEXTURE_FORMAT::BC4_TYPELESS, VK_FORMAT_BC4_UNORM_BLOCK);
            set(TEXTURE_FORMAT::BC4_UNORM, VK_FORMAT_BC4_UNORM_BLOCK);
            set(TEXTURE_FORMAT::BC4_SNORM, VK_FORMAT_BC4_SNORM_BLOCK);
            set(TEXTURE_FORMAT::BC5_TYPELESS, VK_FORMAT_BC5_UNORM_BLOCK);
            set(TEXTURE_FORMAT::BC5_UNORM, VK_FORMAT_BC5_UNORM_BLOCK);
            set(TEXTURE_FORMAT::BC5_SNORM, VK_FORMAT_BC5_SNORM_BLOCK);
            set(TEXTURE_FORMAT::B5G6R5_UNORM, VK_FORMAT_B5G6R5_UNORM_PACK16);
            set(TEXTURE_FORMAT::B5G5R5A1_UNORM, VK_FORMAT_B5G5R5A1_UNORM_PACK16);
            set(TEXTURE_FORMAT::BGRA8_UNORM, VK_FORMAT_B8G8R8A8_UNORM);
            set(TEXTURE_FORMAT::BGRX8_UNORM, VK_FORMAT_B8G8R8A8_UNORM);
            set(TEXTURE_FORMAT::R10G10B10_XR_BIAS_A2_UNORM, VK_FORMAT_UNDEFINED);
            set(TEXTURE_FORMAT::BGRA8_TYPELESS, VK_FORMAT_B8G8R8A8_UNORM);
            set(TEXTURE_FORMAT::BGRA8_UNORM_SRGB, VK_FORMAT_B8G8R8A8_SRGB);
            set(TEXTURE_FORMAT::BGRX8_TYPELESS, VK_FORMAT_B8G8R8A8_UNORM);
            set(TEXTURE_FORMAT::BGRX8_UNORM_SRGB, VK_FORMAT_B8G8R8A8_SRGB);
            set(TEXTURE_FORMAT::BC6H_TYPELESS, VK_FORMAT_BC6H_UFLOAT_BLOCK);
            set(TEXTURE_FORMAT::BC6H_UF16, VK_FORMAT_BC6H_UFLOAT_BLOCK);
            set(TEXTURE_FORMAT::BC6H_SF16, VK_FORMAT_BC6H_SFLOAT_BLOCK);
            set(TEXTURE_FORMAT::BC7_TYPELESS, VK_FORMAT_BC7_UNORM_BLOCK);
            set(TEXTURE_FORMAT::BC7_UNORM, VK_FORMAT_BC7_UNORM_BLOCK);
            set(TEXTURE_FORMAT::BC7_UNORM_SRGB, VK_FORMAT_BC7_SRGB_BLOCK);
            // clang-format on
        }

        VkFormat operator[](TEXTURE_FORMAT TexFmt) const
        {
            u64 lkupVal = u64(TexFmt);
            WB_ASSERT(lkupVal < _countof(lookup))(lkupVal, _countof(lookup));
            return lookup[lkupVal];
        }

    private:
        void set(TEXTURE_FORMAT k, VkFormat v) {
            lookup[u64(k)] = v;
        }

        VkFormat lookup[u64(TEXTURE_FORMAT::NUM_FORMATS)] = {};
    };

    // lookup available call
    VkFormat TexFormatToVkFormat(TEXTURE_FORMAT TexFmt)
    {
        static const TexFormatToVkFormatMapper FmtMapper;
        return FmtMapper[TexFmt];
    }

    class VkFormatToTexFormatMapper {
    public:
        VkFormatToTexFormatMapper()
        {
            // clang-format off
            lookup[VK_FORMAT_UNDEFINED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R4G4_UNORM_PACK8] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R4G4B4A4_UNORM_PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B4G4R4A4_UNORM_PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R5G6B5_UNORM_PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B5G6R5_UNORM_PACK16] = TEXTURE_FORMAT::B5G6R5_UNORM;
            lookup[VK_FORMAT_R5G5B5A1_UNORM_PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B5G5R5A1_UNORM_PACK16] = TEXTURE_FORMAT::B5G5R5A1_UNORM;
            lookup[VK_FORMAT_A1R5G5B5_UNORM_PACK16] = TEXTURE_FORMAT::UNKNOWN;

            lookup[VK_FORMAT_R8_UNORM] = TEXTURE_FORMAT::R8_UNORM;
            lookup[VK_FORMAT_R8_SNORM] = TEXTURE_FORMAT::R8_SNORM;
            lookup[VK_FORMAT_R8_USCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R8_SSCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R8_UINT] = TEXTURE_FORMAT::R8_UINT;
            lookup[VK_FORMAT_R8_SINT] = TEXTURE_FORMAT::R8_SINT;
            lookup[VK_FORMAT_R8_SRGB] = TEXTURE_FORMAT::UNKNOWN;

            lookup[VK_FORMAT_R8G8_UNORM] = TEXTURE_FORMAT::RG8_UNORM;
            lookup[VK_FORMAT_R8G8_SNORM] = TEXTURE_FORMAT::RG8_SNORM;
            lookup[VK_FORMAT_R8G8_USCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R8G8_SSCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R8G8_UINT] = TEXTURE_FORMAT::RG8_UINT;
            lookup[VK_FORMAT_R8G8_SINT] = TEXTURE_FORMAT::RG8_SINT;
            lookup[VK_FORMAT_R8G8_SRGB] = TEXTURE_FORMAT::UNKNOWN;

            lookup[VK_FORMAT_R8G8B8_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R8G8B8_SNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R8G8B8_USCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R8G8B8_SSCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R8G8B8_UINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R8G8B8_SINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R8G8B8_SRGB] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B8G8R8_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B8G8R8_SNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B8G8R8_USCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B8G8R8_SSCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B8G8R8_UINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B8G8R8_SINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B8G8R8_SRGB] = TEXTURE_FORMAT::UNKNOWN;

            lookup[VK_FORMAT_R8G8B8A8_UNORM] = TEXTURE_FORMAT::RGBA8_UNORM;
            lookup[VK_FORMAT_R8G8B8A8_SNORM] = TEXTURE_FORMAT::RGBA8_SNORM;
            lookup[VK_FORMAT_R8G8B8A8_USCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R8G8B8A8_SSCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R8G8B8A8_UINT] = TEXTURE_FORMAT::RGBA8_UINT;
            lookup[VK_FORMAT_R8G8B8A8_SINT] = TEXTURE_FORMAT::RGBA8_SINT;
            lookup[VK_FORMAT_R8G8B8A8_SRGB] = TEXTURE_FORMAT::RGBA8_UNORM_SRGB;

            lookup[VK_FORMAT_B8G8R8A8_UNORM] = TEXTURE_FORMAT::BGRA8_UNORM;
            lookup[VK_FORMAT_B8G8R8A8_SNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B8G8R8A8_USCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B8G8R8A8_SSCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B8G8R8A8_UINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B8G8R8A8_SINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_B8G8R8A8_SRGB] = TEXTURE_FORMAT::BGRA8_UNORM_SRGB;

            lookup[VK_FORMAT_A8B8G8R8_UNORM_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A8B8G8R8_SNORM_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A8B8G8R8_USCALED_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A8B8G8R8_SSCALED_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A8B8G8R8_UINT_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A8B8G8R8_SINT_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A8B8G8R8_SRGB_PACK32] = TEXTURE_FORMAT::UNKNOWN;

            lookup[VK_FORMAT_A2R10G10B10_UNORM_PACK32] = TEXTURE_FORMAT::RGB10A2_UNORM;
            lookup[VK_FORMAT_A2R10G10B10_SNORM_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A2R10G10B10_USCALED_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A2R10G10B10_SSCALED_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A2R10G10B10_UINT_PACK32] = TEXTURE_FORMAT::RGB10A2_UINT;
            lookup[VK_FORMAT_A2R10G10B10_SINT_PACK32] = TEXTURE_FORMAT::UNKNOWN;

            lookup[VK_FORMAT_A2B10G10R10_UNORM_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A2B10G10R10_SNORM_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A2B10G10R10_USCALED_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A2B10G10R10_SSCALED_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A2B10G10R10_UINT_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_A2B10G10R10_SINT_PACK32] = TEXTURE_FORMAT::UNKNOWN;

            lookup[VK_FORMAT_R16_UNORM] = TEXTURE_FORMAT::R16_UNORM;
            lookup[VK_FORMAT_R16_SNORM] = TEXTURE_FORMAT::R16_SNORM;
            lookup[VK_FORMAT_R16_USCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R16_SSCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R16_UINT] = TEXTURE_FORMAT::R16_UINT;
            lookup[VK_FORMAT_R16_SINT] = TEXTURE_FORMAT::R16_SINT;
            lookup[VK_FORMAT_R16_SFLOAT] = TEXTURE_FORMAT::R16_FLOAT;

            lookup[VK_FORMAT_R16G16_UNORM] = TEXTURE_FORMAT::RG16_UNORM;
            lookup[VK_FORMAT_R16G16_SNORM] = TEXTURE_FORMAT::RG16_SNORM;
            lookup[VK_FORMAT_R16G16_USCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R16G16_SSCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R16G16_UINT] = TEXTURE_FORMAT::RG16_UINT;
            lookup[VK_FORMAT_R16G16_SINT] = TEXTURE_FORMAT::RG16_SINT;
            lookup[VK_FORMAT_R16G16_SFLOAT] = TEXTURE_FORMAT::RG16_FLOAT;

            lookup[VK_FORMAT_R16G16B16_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R16G16B16_SNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R16G16B16_USCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R16G16B16_SSCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R16G16B16_UINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R16G16B16_SINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R16G16B16_SFLOAT] = TEXTURE_FORMAT::UNKNOWN;

            lookup[VK_FORMAT_R16G16B16A16_UNORM] = TEXTURE_FORMAT::RGBA16_UNORM;
            lookup[VK_FORMAT_R16G16B16A16_SNORM] = TEXTURE_FORMAT::RGBA16_SNORM;
            lookup[VK_FORMAT_R16G16B16A16_USCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R16G16B16A16_SSCALED] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R16G16B16A16_UINT] = TEXTURE_FORMAT::RGBA16_UINT;
            lookup[VK_FORMAT_R16G16B16A16_SINT] = TEXTURE_FORMAT::RGBA16_SINT;
            lookup[VK_FORMAT_R16G16B16A16_SFLOAT] = TEXTURE_FORMAT::RGBA16_FLOAT;

            lookup[VK_FORMAT_R32_UINT] = TEXTURE_FORMAT::R32_UINT;
            lookup[VK_FORMAT_R32_SINT] = TEXTURE_FORMAT::R32_SINT;
            lookup[VK_FORMAT_R32_SFLOAT] = TEXTURE_FORMAT::R32_FLOAT;

            lookup[VK_FORMAT_R32G32_UINT] = TEXTURE_FORMAT::RG32_UINT;
            lookup[VK_FORMAT_R32G32_SINT] = TEXTURE_FORMAT::RG32_SINT;
            lookup[VK_FORMAT_R32G32_SFLOAT] = TEXTURE_FORMAT::RG32_FLOAT;
            lookup[VK_FORMAT_R32G32B32_UINT] = TEXTURE_FORMAT::RGB32_UINT;
            lookup[VK_FORMAT_R32G32B32_SINT] = TEXTURE_FORMAT::RGB32_SINT;
            lookup[VK_FORMAT_R32G32B32_SFLOAT] = TEXTURE_FORMAT::RGB32_FLOAT;

            lookup[VK_FORMAT_R32G32B32A32_UINT] = TEXTURE_FORMAT::RGBA32_UINT;
            lookup[VK_FORMAT_R32G32B32A32_SINT] = TEXTURE_FORMAT::RGBA32_SINT;
            lookup[VK_FORMAT_R32G32B32A32_SFLOAT] = TEXTURE_FORMAT::RGBA32_FLOAT;

            lookup[VK_FORMAT_R64_UINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R64_SINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R64_SFLOAT] = TEXTURE_FORMAT::UNKNOWN;

            lookup[VK_FORMAT_R64G64_UINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R64G64_SINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R64G64_SFLOAT] = TEXTURE_FORMAT::UNKNOWN;

            lookup[VK_FORMAT_R64G64B64_UINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R64G64B64_SINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R64G64B64_SFLOAT] = TEXTURE_FORMAT::UNKNOWN;

            lookup[VK_FORMAT_R64G64B64A64_UINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R64G64B64A64_SINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_R64G64B64A64_SFLOAT] = TEXTURE_FORMAT::UNKNOWN;

            lookup[VK_FORMAT_B10G11R11_UFLOAT_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_E5B9G9R9_UFLOAT_PACK32] = TEXTURE_FORMAT::RGB9E5_SHAREDEXP;
            lookup[VK_FORMAT_D16_UNORM] = TEXTURE_FORMAT::D16_UNORM;
            lookup[VK_FORMAT_X8_D24_UNORM_PACK32] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_D32_SFLOAT] = TEXTURE_FORMAT::D32_FLOAT;
            lookup[VK_FORMAT_S8_UINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_D16_UNORM_S8_UINT] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_D24_UNORM_S8_UINT] = TEXTURE_FORMAT::D24_UNORM_S8_UINT;
            lookup[VK_FORMAT_D32_SFLOAT_S8_UINT] = TEXTURE_FORMAT::D32_FLOAT_S8X24_UINT;

            lookup[VK_FORMAT_BC1_RGB_UNORM_BLOCK] = TEXTURE_FORMAT::BC1_UNORM;
            lookup[VK_FORMAT_BC1_RGB_SRGB_BLOCK] = TEXTURE_FORMAT::BC1_UNORM_SRGB;
            lookup[VK_FORMAT_BC1_RGBA_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_BC1_RGBA_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_BC2_UNORM_BLOCK] = TEXTURE_FORMAT::BC2_UNORM;
            lookup[VK_FORMAT_BC2_SRGB_BLOCK] = TEXTURE_FORMAT::BC2_UNORM_SRGB;
            lookup[VK_FORMAT_BC3_UNORM_BLOCK] = TEXTURE_FORMAT::BC3_UNORM;
            lookup[VK_FORMAT_BC3_SRGB_BLOCK] = TEXTURE_FORMAT::BC3_UNORM_SRGB;
            lookup[VK_FORMAT_BC4_UNORM_BLOCK] = TEXTURE_FORMAT::BC4_UNORM;
            lookup[VK_FORMAT_BC4_SNORM_BLOCK] = TEXTURE_FORMAT::BC4_SNORM;
            lookup[VK_FORMAT_BC5_UNORM_BLOCK] = TEXTURE_FORMAT::BC5_UNORM;
            lookup[VK_FORMAT_BC5_SNORM_BLOCK] = TEXTURE_FORMAT::BC5_SNORM;
            lookup[VK_FORMAT_BC6H_UFLOAT_BLOCK] = TEXTURE_FORMAT::BC6H_UF16;
            lookup[VK_FORMAT_BC6H_SFLOAT_BLOCK] = TEXTURE_FORMAT::BC6H_SF16;
            lookup[VK_FORMAT_BC7_UNORM_BLOCK] = TEXTURE_FORMAT::BC7_UNORM;
            lookup[VK_FORMAT_BC7_SRGB_BLOCK] = TEXTURE_FORMAT::BC7_UNORM_SRGB;

            lookup[VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_EAC_R11_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_EAC_R11_SNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_EAC_R11G11_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_EAC_R11G11_SNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_4x4_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_4x4_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_5x4_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_5x4_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_5x5_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_5x5_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_6x5_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_6x5_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_6x6_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_6x6_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_8x5_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_8x5_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_8x6_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_8x6_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_8x8_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_8x8_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_10x5_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_10x5_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_10x6_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_10x6_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_10x8_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_10x8_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_10x10_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_10x10_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_12x10_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_12x10_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_12x12_UNORM_BLOCK] = TEXTURE_FORMAT::UNKNOWN;
            lookup[VK_FORMAT_ASTC_12x12_SRGB_BLOCK] = TEXTURE_FORMAT::UNKNOWN;



            lookupExt[VK_FORMAT_G8B8G8R8_422_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_B8G8R8G8_422_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G8_B8R8_2PLANE_420_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G8_B8R8_2PLANE_422_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_R10X6_UNORM_PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_R10X6G10X6_UNORM_2PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_R12X4_UNORM_PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_R12X4G12X4_UNORM_2PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G16B16G16R16_422_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_B16G16R16G16_422_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G16_B16R16_2PLANE_420_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G16_B16R16_2PLANE_422_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG] = TEXTURE_FORMAT::UNKNOWN;
            lookupExt[VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG] = TEXTURE_FORMAT::UNKNOWN;
            // clang-format on
        }

        TEXTURE_FORMAT operator[](VkFormat VkFmt) const
        {
            if (VkFmt < VK_FORMAT_RANGE_SIZE)
            {
                return lookup[VkFmt];
            } else
            {
                auto it = lookupExt.find(VkFmt);
                return it != lookupExt.end() ? it->second : TEXTURE_FORMAT::UNKNOWN;
            }
        }

    private:
        TEXTURE_FORMAT                               lookup[VK_FORMAT_RANGE_SIZE] = {};
        std::unordered_map<VkFormat, TEXTURE_FORMAT> lookupExt;
    };

    // lookup available call
    TEXTURE_FORMAT VkFormatToTexFormat(VkFormat VkFmt)
    {
        static const VkFormatToTexFormatMapper FmtMapper;
        return FmtMapper[VkFmt];
    }

    
    SURFACE_TRANSFORM VkSurfaceTransformFlagToSurfaceTransform(VkSurfaceTransformFlagBitsKHR vkTransformFlag)
    {
        // TODO (Chris): assert input is power-of-two
        // clang-format off
        switch (vkTransformFlag)
        {
        case VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR:                     return SURFACE_TRANSFORM::IDENTITY;
        case VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR:                    return SURFACE_TRANSFORM::ROTATE_90;
        case VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR:                   return SURFACE_TRANSFORM::ROTATE_180;
        case VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR:                   return SURFACE_TRANSFORM::ROTATE_270;
        case VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR:            return SURFACE_TRANSFORM::HORIZONTAL_MIRROR;
        case VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR:  return SURFACE_TRANSFORM::HORIZONTAL_MIRROR_ROTATE_90;
        case VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR: return SURFACE_TRANSFORM::HORIZONTAL_MIRROR_ROTATE_180;
        case VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR: return SURFACE_TRANSFORM::HORIZONTAL_MIRROR_ROTATE_270;

        default:
            return SURFACE_TRANSFORM::IDENTITY;
        }
        // clang-format on
    }

    VkSurfaceTransformFlagBitsKHR SurfaceTransformToVkSurfaceTransformFlag(SURFACE_TRANSFORM SrfTransform)
    {
        // clang-format off
        switch (SrfTransform)
        {
        case SURFACE_TRANSFORM::OPTIMAL:
            return VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR;

        case SURFACE_TRANSFORM::IDENTITY:                      return VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR;
        case SURFACE_TRANSFORM::ROTATE_90:                     return VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR;
        case SURFACE_TRANSFORM::ROTATE_180:                    return VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR;
        case SURFACE_TRANSFORM::ROTATE_270:                    return VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR;
        case SURFACE_TRANSFORM::HORIZONTAL_MIRROR:             return VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR;
        case SURFACE_TRANSFORM::HORIZONTAL_MIRROR_ROTATE_90:   return VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR;
        case SURFACE_TRANSFORM::HORIZONTAL_MIRROR_ROTATE_180:  return VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR;
        case SURFACE_TRANSFORM::HORIZONTAL_MIRROR_ROTATE_270:  return VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR;

        default:
            return VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR;
        }
        // clang-format on
    }
}